#!/usr/bin/env python


import rospy



from nuturtlebot_msgs.msg import SensorData
from nuturtlebot_msgs.msg import WheelCommands
from sensor_msgs.msg import JointState

from geometry_msgs.msg import Twist

from lqr.koop_train import Turtle_Koop, Turtle_Koop_Vel, Turtle_Koop_Poly

from cartpole.msg import Data


class Simple_Turtle():
    def __init__(self):
        
        self.dt = rospy.get_param('dt')
        self.basis = rospy.get_param('basis')
        
        self.encoder_ticks_to_rad = rospy.get_param('encoder_ticks_to_rad')
        self.motor_cmd_to_radsec = rospy.get_param('motor_cmd_to_radsec')
        
        self.ltheta = 0.
        self.rtheta = 0.
        
        self.lvel = 3.03
        self.rvel = 3.03    
        
        self.lcmd = 126.
        self.rcmd = 126.

        self.encoder_sub =  rospy.Subscriber('/sensor_data', SensorData, self.encoder_callback)
        self.cmd_sub = rospy.Subscriber('/wheel_cmd', WheelCommands, self.cmd_callback)
        self.joint_sub = rospy.Subscriber('/blue/joint_states', JointState, self.joint_callback)
        
        self.twist_pub = rospy.Publisher('/cmd_vel', Twist, queue_size = 10)
        self.data_l_pub = rospy.Publisher('/l_data', Data, queue_size=10000)
        self.data_r_pub = rospy.Publisher('/r_data', Data, queue_size=10000)
        self.data_lv_pub = rospy.Publisher('lv_data', Data, queue_size=10000)
        self.data_rv_pub = rospy.Publisher('rv_data', Data, queue_size=10000)
        

        self.first = True
        
        if self.basis == 'fourier':
            self.koopman = Turtle_Koop_Vel(self.dt, 4, 2, self.ltheta, self.rtheta, self.lvel, self.rvel, self.lcmd, self.rcmd)
        if self.basis == 'poly':
            self.koopman = Turtle_Koop_Poly(self.dt, 4, 2, self.ltheta, self.rtheta, self.lvel, self.rvel, self.lcmd, self.rcmd)
  
        
        self.l_first = 0.
        self.r_first = 0.
        
        self.iteration = 0
        
    def joint_callback(self,data):
        """Get JointState

        Args:
            data (float): turtlebot joint states
        """
        self.lvel = data.velocity[0]
        self.rvel = data.velocity[1]
        
        if self.lvel<1.:
            self.lvel = 3.030
        if self.rvel<1.:
            self.rvel = 3.030
            
        
        self.data_lv_pub.publish(self.lvel)
        self.data_rv_pub.publish(self.rvel)
        # print(self.lvel)
        # print(self.rvel)
        
    def encoder_callback(self,data):
        """encoder turtlebot data

        Args:
            data (nuturtlebot_msg): encoder data from turtlebot
        """
        
        t = Twist()
        t.linear.x = 0.1
        t.linear.y = 0.
        t.linear.z = 0.
        
        t.angular.x = 0.
        t.angular.y = 0.
        t.angular.z = 0.
        
        self.twist_pub.publish(t)
        
        
        self.ltheta_old = self.ltheta
        self.rtheta_old = self.rtheta
        
        self.ltheta = data.left_encoder
        self.rtheta = data.right_encoder  

        
        if self.first == True:
            self.l_first = self.ltheta
            self.r_first = self.rtheta
            self.first = False
        
        print("right angle: ", (self.ltheta - self.l_first))
        print("left angle: ", (self.rtheta - self.r_first))
        
        self.data_l_pub.publish((self.ltheta - self.l_first))
        self.data_r_pub.publish((self.rtheta - self.r_first))
        
        self.iteration+=1
        print('iteration: ', self.iteration)
        self.koopman.train_model((self.ltheta - self.l_first), (self.rtheta - self.r_first), self.lvel, self.rvel, self.lcmd, self.rcmd)
        self.koopman.calculateK()
        

        
    def cmd_callback(self, data):
        """motor command callback

        Args:
            data (WheelCommands): input commands to system
        """
        
        self.lcmd = float(data.left_velocity)
        self.rcmd = float(data.right_velocity)
        
        
        # print('rcmd: ', self.rcmd*self.motor_cmd_to_radsec)
        # print('lcmd: ', self.lcmd*self.motor_cmd_to_radsec)
        
        
        
def main():
    """
    Main function
    """
    rospy.init_node('simple_turtle')
    simple = Simple_Turtle()
    rospy.spin()

if __name__ == '__main__':
    main()